Add basic decoding and visualization of trip planning response
the-mace/rivian-python-api pull request #3
Opened 2023-04-02 23:05 UTC by doggkruse

Display via mapbox if MAPBOX_API_KEY is provided in .env

2023-04-12 11:21 UTC, the-mace requested changes
Would you mind making the suggested changes?

2023-04-12 11:21 UTC, the-mace commented on README.md
> +bin/rivian_cli --plan_trip 85,225,40.5112,-89.0559,39.9310,-104.9530
The first coordinate looks like Rivian, but the second is perhaps a personal address. I'd suggest against any personal addresses (or vins, etc) in examples/data.

2023-04-12 11:21 UTC, the-mace commented on src/rivian_python_api/rivian_map.py
> +import polyline
Needs to be added to requirements.txt

2023-04-12 11:21 UTC, the-mace commented on src/rivian_python_api/rivian_map.py
> +import plotly.graph_objects as go
Also needs to be in requirements.txt

2023-04-12 18:07 UTC, doggkruse commented on README.md
> +bin/rivian_cli --plan_trip 85,225,40.5112,-89.0559,39.9310,-104.9530
I agree!  The second coordinate is the Rivian Service center in Colorado so should be OK as is

2023-04-12 18:08 UTC, doggkruse commented on src/rivian_python_api/rivian_map.py
> +import polyline
requirements.txt does not exist in the repo (maybe .gitignore?) would you like me to create it or if you'd like to add the existing I can update.

2023-04-12 18:08 UTC, doggkruse commented on src/rivian_python_api/rivian_map.py
> +import plotly.graph_objects as go
Same as above

2023-04-12 18:47 UTC, doggkruse commented
Added requirements.txt

2023-04-13 00:23 UTC, the-mace commented
Nice, thank you!

2023-04-13 00:24 UTC, merged